name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Install dependencies
      run: pnpm install

    - name: Run linter
      run: pnpm run lint

    - name: Run tests
      run: pnpm run test

    - name: Build
      run: pnpm run build

    - name: Publish to NPM
      if: success()
      run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}